"""empty message

Revision ID: a679db097968
Revises: 
Create Date: 2017-03-14 20:21:31.542521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a679db097968'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vistors',
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('visitor_ip', sa.Text(), nullable=True),
    sa.Column('first_visit_time', sa.DateTime(), nullable=True),
    sa.Column('last_visit_time', sa.DateTime(), nullable=True),
    sa.Column('visit_counts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('visitor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vistors')
    # ### end Alembic commands ###
